    name: CI

    on:
        pull_request:
        push:

    jobs:
        lint:
            runs-on: ubuntu-latest
            strategy:
                matrix:
                    node-version: [16.x]
            steps:
                - uses: actions/checkout@v2
                - uses: actions/setup-node@v1
                  with:
                      node-version: ${{ matrix.node-version }}
                - run: npm ci
                - run: npm run lint:check

        test_build:
            runs-on: ubuntu-latest
            strategy:
                matrix:
                    node-version: [16.x]
            steps:
                - uses: actions/checkout@v2
                - uses: actions/setup-node@v1
                  with:
                      node-version: ${{ matrix.node-version }}
                - run: npm ci
                - run: npm run build

        test_deploy:
            runs-on: ubuntu-latest
            strategy:
                matrix:
                    node-version: [ 16.x ]
            steps:
                - uses: actions/checkout@v2
                - uses: actions/setup-node@v1
                  with:
                      node-version: ${{ matrix.node-version }}
                - run: npm ci
                - run: npm run build
                - run: |
                    cd dist
                    ls
